using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Forms;
using DevExpress.XtraGrid.Menu;
using DevExpress.Utils.Menu;
using DevExpress.XtraGrid.Views.Grid;
using Prog_Areas_Proyecto.Controllers;
using Prog_Areas_Proyecto.Modelos;
using Prog_Areas_Proyecto.DataSets;

namespace Prog_Areas.Formularios
{
    public partial class ProjectListingView : DevExpress.XtraEditors.XtraUserControl
    {
        DataSetProyectos.obrasRow obra;
        public ProjectListingView()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            obrasTableAdapter1.FillAllObras(dataSetProyectos1.obras);
            //gridView1.Columns[2].GroupIndex = 1;
            
        }

        private void dataGridView1_CellContentClick(object sender, DataGridViewCellEventArgs e)
        {
            //var senderGrid = (DataGridView)sender;

            //if (senderGrid.Columns[e.ColumnIndex] is DataGridViewButtonColumn && e.RowIndex >= 0)
            //{
            //    //MessageBox.Show(dataGridView1.Rows[e.RowIndex].Cells[0].Value.ToString());
            //    Proyecto _proyecto = new Proyecto()
            //    {
            //        Nombre = dataGridView1.Rows[e.RowIndex].Cells[0].Value.ToString(),
            //        Cod = dataGridView1.Rows[e.RowIndex].Cells[1].Value.ToString(),
            //        Cant_habitaciones = int.Parse(dataGridView1.Rows[e.RowIndex].Cells[2].Value.ToString())
            //    };
            //    MainView.Instance().renderPanel.Controls.Clear();
            //    MainView.Instance().renderPanel.Controls.Add(new ProjectManagementView(_proyecto));
            //}
        }

        private void gridView1_DoubleClick(object sender, EventArgs e)
        {
            
        }

        private void gridView1_RowCellClick(object sender, DevExpress.XtraGrid.Views.Grid.RowCellClickEventArgs e)
        {
            
        }

        private void gridView1_PopupMenuShowing(object sender, DevExpress.XtraGrid.Views.Grid.PopupMenuShowingEventArgs e)
        {
            GridView _grid = gridControl1.FocusedView as GridView;
            
            obra = _grid.FocusedRowHandle == -2147483646 ? obrasTableAdapter1.GetDataByID(int.Parse(gridView1.GetRowCellValue(0, "idobra").ToString())).FirstOrDefault() : obrasTableAdapter1.GetDataByID(int.Parse(gridView1.GetRowCellValue(_grid.FocusedRowHandle, "idobra").ToString())).FirstOrDefault();

            switch (e.MenuType)
            {
                case GridMenuType.Row:
                    var menu = e.Menu as GridViewMenu;
                    menu.Items.Clear();
                    menu.Items.Add(CreateItem("Modificar"));
                    break;
            }
        }



        DXMenuItem CreateItem(string name)
        {
            DXMenuItem item = null;
            switch (name)
            {
                case "Modificar":
                    item = new DXMenuItem(name, new EventHandler(MostrarDetalles));
                    break;
                
            }

            return item;
        }

        void MostrarDetalles(object sender, EventArgs e)
        {
            if (ProyectoController.IsNewProject(obra.idobra))
            {
                Form _addProject = new AddProjectForm(obra);
                _addProject.ShowDialog();
            }
            else
            {
                var _proyecto = ProyectoController.UpdateProyecto(obra);
                Form _projectManagement = new ProjectManagementForm(_proyecto);
                _projectManagement.ShowDialog();
            }

        }
    }
}
