//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aire_Fresco
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aire_Fresco()
        {
            this.Climatizacion = new HashSet<Climatizacion>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Persona { get; set; }
        public Nullable<int> Metro_Cuadrado { get; set; }
    
        public virtual AF_Metro_Cuadrado AF_Metro_Cuadrado { get; set; }
        public virtual AF_Persona AF_Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Climatizacion> Climatizacion { get; set; }
    }
}
