//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambiente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ambiente()
        {
            this.Local = new HashSet<Local>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Suelo { get; set; }
        public Nullable<int> Rodapie { get; set; }
        public Nullable<int> Pared { get; set; }
        public Nullable<int> Techo { get; set; }
        public Nullable<int> Impermeable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Local> Local { get; set; }
    }
}
