//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Climatizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Climatizacion()
        {
            this.Local = new HashSet<Local>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Tratamiento { get; set; }
        public Nullable<int> Equipamiento { get; set; }
        public Nullable<int> Criterio { get; set; }
        public Nullable<int> Aire_Fresco { get; set; }
        public Nullable<int> Renovaciones { get; set; }
        public Nullable<int> W_Aire { get; set; }
    
        public virtual Aire_Fresco Aire_Fresco1 { get; set; }
        public virtual Criterio Criterio1 { get; set; }
        public virtual Equipamiento Equipamiento1 { get; set; }
        public virtual Renovaciones Renovaciones1 { get; set; }
        public virtual Tratamiento Tratamiento1 { get; set; }
        public virtual W_Aire W_Aire1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Local> Local { get; set; }
    }
}
