//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunicaciones_Tv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comunicaciones_Tv()
        {
            this.Local = new HashSet<Local>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Tf { get; set; }
        public Nullable<int> Td { get; set; }
        public Nullable<int> TD_Pos { get; set; }
        public Nullable<int> UPSC { get; set; }
        public Nullable<int> TT_TV { get; set; }
        public Nullable<int> Di { get; set; }
        public Nullable<int> Altv { get; set; }
        public Nullable<int> UPSI { get; set; }
    
        public virtual ALTV ALTV1 { get; set; }
        public virtual DI DI1 { get; set; }
        public virtual TD TD1 { get; set; }
        public virtual TD_Pos TD_Pos1 { get; set; }
        public virtual TF TF1 { get; set; }
        public virtual TT_TV TT_TV1 { get; set; }
        public virtual UPSC UPSC1 { get; set; }
        public virtual UPSI UPSI1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Local> Local { get; set; }
    }
}
