//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Local()
        {
            this.Locales_Proyecto = new HashSet<Locales_Proyecto>();
        }
    
        public int RoomId { get; set; }
        public string Key_Name { get; set; }
        public Nullable<bool> Habitacion { get; set; }
        public Nullable<int> SubsistemaTipo { get; set; }
        public Nullable<int> SubsistemaArea { get; set; }
        public Nullable<int> Climatizacion { get; set; }
        public Nullable<int> Comunicaciones_TV { get; set; }
        public Nullable<int> Ambiente { get; set; }
        public Nullable<int> Coef_Area { get; set; }
        public Nullable<int> Mod { get; set; }
        public Nullable<int> Tipo_Edificio { get; set; }
        public Nullable<int> Porciento_BD { get; set; }
        public Nullable<int> Alojamiento { get; set; }
        public Nullable<int> Local_Tipo { get; set; }
        public int Id { get; set; }
        public Nullable<int> Desglose { get; set; }
        public Nullable<int> Grupo_Local { get; set; }
    
        public virtual Alojamiento Alojamiento1 { get; set; }
        public virtual Ambiente Ambiente1 { get; set; }
        public virtual Climatizacion Climatizacion1 { get; set; }
        public virtual CoefArea CoefArea { get; set; }
        public virtual Comunicaciones_Tv Comunicaciones_Tv1 { get; set; }
        public virtual Desglose Desglose1 { get; set; }
        public virtual LocalTipo LocalTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locales_Proyecto> Locales_Proyecto { get; set; }
    }
}
