//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locales_Proyecto
    {
        public int Id { get; set; }
        public Nullable<int> Proyecto { get; set; }
        public Nullable<int> Local { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Local Local1 { get; set; }
        public virtual Proyecto Proyecto1 { get; set; }
    }
}
