//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Proyecto.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BIM : DbContext
    {
        public DB_BIM()
            : base("name=DB_BIM")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AF_Metro_Cuadrado> AF_Metro_Cuadrado { get; set; }
        public virtual DbSet<AF_Persona> AF_Persona { get; set; }
        public virtual DbSet<Aire_Fresco> Aire_Fresco { get; set; }
        public virtual DbSet<Alojamiento> Alojamiento { get; set; }
        public virtual DbSet<Alojamiento_Tipo> Alojamiento_Tipo { get; set; }
        public virtual DbSet<ALTV> ALTV { get; set; }
        public virtual DbSet<Ambiente> Ambiente { get; set; }
        public virtual DbSet<Climatizacion> Climatizacion { get; set; }
        public virtual DbSet<CoefArea> CoefArea { get; set; }
        public virtual DbSet<Comunicaciones_Tv> Comunicaciones_Tv { get; set; }
        public virtual DbSet<Criterio> Criterio { get; set; }
        public virtual DbSet<Desglose> Desglose { get; set; }
        public virtual DbSet<DI> DI { get; set; }
        public virtual DbSet<Equipamiento> Equipamiento { get; set; }
        public virtual DbSet<Local> Local { get; set; }
        public virtual DbSet<Locales_Proyecto> Locales_Proyecto { get; set; }
        public virtual DbSet<LocalTipo> LocalTipo { get; set; }
        public virtual DbSet<Proyecto> Proyecto { get; set; }
        public virtual DbSet<Renovaciones> Renovaciones { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TD> TD { get; set; }
        public virtual DbSet<TD_Pos> TD_Pos { get; set; }
        public virtual DbSet<TF> TF { get; set; }
        public virtual DbSet<Tratamiento> Tratamiento { get; set; }
        public virtual DbSet<TT_TV> TT_TV { get; set; }
        public virtual DbSet<UPSC> UPSC { get; set; }
        public virtual DbSet<UPSI> UPSI { get; set; }
        public virtual DbSet<W_Aire> W_Aire { get; set; }
    }
}
