//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Proyecto.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proyecto()
        {
            this.Desglose = new HashSet<Desglose>();
            this.Locales_Proyecto = new HashSet<Locales_Proyecto>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Cod { get; set; }
        public Nullable<int> Cant_Habitaciones { get; set; }
        public string Localizacion { get; set; }
        public Nullable<System.DateTime> Fecha_Comienzo { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public Nullable<double> Superficie_Parcela { get; set; }
        public Nullable<int> Categoria { get; set; }
        public string Tipo_Hotel { get; set; }
        public string Subtipo_Alojamiento { get; set; }
        public string Tipo_Alojamiento { get; set; }
        public Nullable<int> Maxima_Altura { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Desglose> Desglose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Locales_Proyecto> Locales_Proyecto { get; set; }
    }
}
