//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Plantilla.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Ambiente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Ambiente()
        {
            this.T_Local = new HashSet<T_Local>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Suelo { get; set; }
        public Nullable<int> Rodapie { get; set; }
        public Nullable<int> Pared { get; set; }
        public Nullable<int> Techo { get; set; }
        public Nullable<int> Impermeable { get; set; }
    
        public virtual T_Catalogo_Impermeable T_Catalogo_Impermeable { get; set; }
        public virtual T_Catalogo_Pared T_Catalogo_Pared { get; set; }
        public virtual T_Catalogo_Rodapie T_Catalogo_Rodapie { get; set; }
        public virtual T_Catalogo_Suelo T_Catalogo_Suelo { get; set; }
        public virtual T_Catalogo_Techo T_Catalogo_Techo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Local> T_Local { get; set; }
    }
}
