//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Plantilla.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Climatizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Climatizacion()
        {
            this.T_Local = new HashSet<T_Local>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Tratamiento { get; set; }
        public Nullable<int> Equipamiento { get; set; }
        public Nullable<int> Criterio { get; set; }
        public Nullable<int> Aire_Fresco { get; set; }
        public Nullable<int> Renovaciones { get; set; }
        public Nullable<int> W_Aire { get; set; }
    
        public virtual T_Aire_Fresco T_Aire_Fresco { get; set; }
        public virtual T_Criterio T_Criterio { get; set; }
        public virtual T_Equipamiento T_Equipamiento { get; set; }
        public virtual T_Renovaciones T_Renovaciones { get; set; }
        public virtual T_Tratamiento T_Tratamiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Local> T_Local { get; set; }
        public virtual T_W_Aire T_W_Aire { get; set; }
    }
}
