//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog_Areas_Plantilla.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Comunicaciones_Tv
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Comunicaciones_Tv()
        {
            this.T_Local = new HashSet<T_Local>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Tf { get; set; }
        public Nullable<int> Td { get; set; }
        public Nullable<int> TD_Pos { get; set; }
        public Nullable<int> UPSC { get; set; }
        public Nullable<int> TT_TV { get; set; }
        public Nullable<int> Di { get; set; }
        public Nullable<int> Altv { get; set; }
        public Nullable<int> UPSI { get; set; }
    
        public virtual T_ALTV T_ALTV { get; set; }
        public virtual T_DI T_DI { get; set; }
        public virtual T_TD T_TD { get; set; }
        public virtual T_TD_Pos T_TD_Pos { get; set; }
        public virtual T_TF T_TF { get; set; }
        public virtual T_TT_TV T_TT_TV { get; set; }
        public virtual T_UPSC T_UPSC { get; set; }
        public virtual T_UPSI T_UPSI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Local> T_Local { get; set; }
    }
}
